name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  GODOT_VERSION: 4.3-beta2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - run: curl -o godotsteam.zip -L https://github.com/GodotSteam/GodotSteam/releases/download/v4.8-gde/godotsteam-gdextension-plugin.zip
      - run: unzip godotsteam.zip

      - run: curl -o godot.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_win64.exe.zip
      - run: unzip godot.zip
      - run: curl -o templates.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_export_templates.tpz
      - run: unzip templates.zip "templates/windows*x86_64*" "templates/version.txt"
      - run: mkdir -p C:/Users/runneradmin/AppData/Roaming/Godot/export_templates/$(cat templates/version.txt)
      - run: mv templates/windows* C:/Users/runneradmin/AppData/Roaming/Godot/export_templates/$(cat templates/version.txt)/
      - run: mkdir -p Godottest
      - name: godot build
        continue-on-error: true
        run: ./Godot_v${{env.GODOT_VERSION}}_win64_console.exe -v --headless --export-release "Windows Desktop" ./Godottest/Godottest.exe

      - run: ls
      - run: ls Godottest

      # - run: Compress-Archive Godottest Godottest.zip
      # - run: ls

      - uses: actions/upload-artifact@v4
        with:
          name: Godottest
          path: Godottest/
          if-no-files-found: error

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4

      - name: install steamcmd
        run: |
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections
          sudo add-apt-repository multiverse
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install steamcmd
          mkdir -p ~/Steam/config

      - run: echo "${{ secrets.STEAM_CONFIG_VDF }}" | base64 -d > ~/Steam/config/config.vdf
      - run: sed -i 's/STEAM_APP_ID/${{ secrets.STEAM_APP_ID }}/g' manifest.vdf
      - run: sed -i 's/STEAM_DEPOT/${{ secrets.STEAM_DEPOT }}/g' manifest.vdf
      - run: pwd
      - run: ls
      - run: ls Godottest

      - run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build "$(pwd)/manifest.vdf" +quit
