name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo steam steam/question select "I AGREE" | debconf-set-selections
          echo steam steam/license note '' | debconf-set-selections
          sudo add-apt-repository multiverse
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install steamcmd
