name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4

      - name: install steamcmd
        run: |
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections
          sudo add-apt-repository multiverse
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install steamcmd
          mkdir -p ~/Steam/config

      - run: echo "${{ secrets.STEAM_CONFIG_VDF }}" | base64 -d > ~/Steam/config/config.vdf

      - run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +quit
